version: '3.9'

services:
  db:
    container_name: db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes: 
      - pgdata:/var/lib/postgresql/data
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    env_file:
      - ./backend/.env
volumes:
  pgdata: {}